#Домашнее задание "Основные математические понятия".
##**Уровень 0:**


Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

Игра в имитацию

Ярость

12 лет рабства

Однажды в Голливуде

```
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде
```




In [ ]:
import numpy as np

In [ ]:
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

**Задание 1**

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [ ]:
norm_yar = np.linalg.norm(film_2) #Евклидова норма фильма Ярость
norm_yar

1.4142135623730951

In [ ]:
norm_rab = np.linalg.norm(film_3) #Евклидова норма фильма 12 лет рабства
norm_rab

1.7320508075688772

In [ ]:
skal_yar_rab = np.dot(film_2,film_3) # Скалярное произведение фильма Ярость и 12 лет рабства
skal_yar_rab

1

In [ ]:
cos = skal_yar_rab/(norm_yar*norm_rab)
cos # Косинус угла между векторами

0.40824829046386296

In [ ]:
rad = np.arccos(cos)
rad # Величина угла в радианах

1.1502619915109316

In [ ]:
np.rad2deg(rad) # угол между векторами в градусах

65.90515744788931

##Уровень 1:

**Задание 2**

Вычислить с помощью Python значение первой производной для функции $3x(x^2+x)^3$ в точке $x=1$

In [ ]:
import sympy as sym

In [ ]:
x = sym.Symbol('x')

In [ ]:
3*x*(x**2+x)**3  

3*x*(x**2 + x)**3

In [ ]:
res = sym.diff(3*x*(x**2+x)**3,x)
res

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

In [ ]:
res.subs(x,1)

132

**Задание 3**

Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы.

Умножьте вектор [1,2,3,4] на полученную матрицу

In [ ]:
matrix = np.vstack([film_1 ,film_2 ,film_3 ,film_4])

In [ ]:
matrix

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [ ]:
vector = [1,2,3,4]

In [ ]:
proiz = np.matmul(vector,matrix)
proiz

array([4, 2, 3, 9, 4, 4])

In [ ]:
vector @ matrix

array([4, 2, 3, 9, 4, 4])