#Домашнее задание "Линейная алгебра. Матрицы".

In [ ]:
import numpy as np

##Уровень 0:
**Задание 1**

-Создайте матрицу 3 на 3, заполненную числами от 1 до 9

-Прибавьте к ней матрицу с единицами на диагонале

-Умножьте полученную матрицу на вектор (1, 2, 3)

-Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы

-Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]]) # матрица 3х3
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix_eye = np.eye(3) # единичная матрица
matrix_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
matrix_sum = matrix + matrix_eye  # сумма матриц
matrix_sum

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [ ]:
vector = np.array([1,2,3]) # вектор
vector

array([1, 2, 3])

In [ ]:
mat_poiz = np.matmul(matrix_sum,vector) # матрица умноженная на вектор
mat_poiz

array([15., 34., 53.])

In [ ]:
matrix_transpons = np.transpose(matrix_sum)
matrix_transpons  # транспонированная матрица

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
matrix_inv = np.linalg.inv(matrix_sum) # обратная матрица
matrix_inv

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [ ]:
matrix_inv @ matrix_sum  
# проверяем корректность обратной матрицы(перемножаем исходную матрицу на обратную, должна получиться единичная матрица)

array([[ 1.00000000e+00,  0.00000000e+00,  3.55271368e-15],
       [-7.77156117e-17,  1.00000000e+00,  1.11022302e-16],
       [ 6.66133815e-16,  0.00000000e+00,  1.00000000e+00]])

##Уровень 1:

**Задание 2**

Найдите собственные значения и собственные вектора матрицы:


```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
np.linalg.eigvals(m) # собственные значения матрицы

array([1., 4.])

In [ ]:
np.linalg.eig(m)[1] # собственные вектора матрицы

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

**Задание 3**

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
dot_1 = np.array([[1,2,1],[2,1,1],[1,3,1]])
dot_1

array([[1, 2, 1],
       [2, 1, 1],
       [1, 3, 1]])

In [ ]:
np.linalg.det(dot_1) # определитель матрицы

1.0

In [ ]:
np.linalg.matrix_rank(dot_1) # ранг матрица , все вектора независимы

3