**Загрузите данные.**

Используйте датасет с ирисами. Его можно загрузить непосредственно из библиотеки Sklearn. В данных оставьте только 2 класса: Iris Versicolor, Iris Virginica.

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np

In [ ]:
data = load_iris()

In [ ]:
iris = pd.DataFrame(data=data.data, columns=data.feature_names)

In [ ]:
iris['class']=data.target

In [ ]:
target_names = {0: "Iris-Setosa", 1: "Iris-Versicolour", 2:"Iris-Virginica" }

In [ ]:
iris['class_name']=iris['class'].map(target_names)

In [ ]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class   class_name  
0      0  Iris-Setosa  
1      0  Iris-Setosa  
2      0  Iris-Setosa  
3      0  Iris-Setosa  
4      0  Iris-Setosa

In [ ]:
iris['class_name'].unique()

array(['Iris-Setosa', 'Iris-Versicolour', 'Iris-Virginica'], dtype=object)

In [ ]:
iris_filter = iris.loc[(iris['class_name'] == 'Iris-Versicolour')|
                       (iris['class_name'] == 'Iris-Virginica')]

In [ ]:
iris_filter.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    class        class_name  
50      1  Iris-Versicolour  
51      1  Iris-Versicolour  
52      1  Iris-Versicolour  
53      1  Iris-Versicolour  
54      1  Iris-Versicolour

In [ ]:
iris_filter.sample(frac=1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
68                 6.2               2.2                4.5               1.5   
120                6.9               3.2                5.7               2.3   
58                 6.6               2.9                4.6               1.3   
123                6.3               2.7                4.9               1.8   
110                6.5               3.2                5.1               2.0   
..                 ...               ...                ...               ...   
50                 7.0               3.2                4.7               1.4   
144                6.7               3.3                5.7               2.5   
130                7.4               2.8                6.1               1.9   
89                 5.5               2.5                4.0               1.3   
56                 6.3               3.3                4.7               1.6   

     class        class_name  
68       1  Iris-Versicolour  
120      2    Iris-Virginica  
58       1  Iris-Versicolour  
123      2    Iris-Virginica  
110      2    Iris-Virginica  
..     ...               ...  
50       1  Iris-Versicolour  
144      2    Iris-Virginica  
130      2    Iris-Virginica  
89       1  Iris-Versicolour  
56       1  Iris-Versicolour  

[100 rows x 6 columns]

In [ ]:
iris_filter.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'class', 'class_name'],
      dtype='object')

In [ ]:
iris_filter.loc[(iris_filter['class'] ==2),'class'] = 0

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [ ]:
iris_filter['class'].unique()

array([1, 0])

**Самостоятельно реализуйте логистическую регрессию, без использования метода LogisticRegression из библиотеки**.

 Можете использовать библиотеки pandas, numpy, math для реализации. Оформите в виде функции. *Оформите в виде класса с методами.

In [ ]:
X = np.array(iris_filter[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)']])
y = np.array(iris_filter['class'])

In [ ]:
def loss(h, y):
    return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()

In [ ]:
def sigmoid(X, W):
    z = W[0]+X[:,0]*W[1]+X[:,1]*W[2]+X[:,2]*W[3]+X[:,3]*W[4]
    return 1 / (1 + np.exp(-z))

In [ ]:
W = np.random.randn(X.shape[1]+1)

In [ ]:
W

array([ 0.16527607, -0.45194227,  0.07675184, -1.93074826,  0.48753324])

In [ ]:
result1 = sigmoid(X, W)

In [ ]:
f1 = pd.DataFrame(result1)
f1['pred'] = f1[0].apply(lambda x : 0 if x < 0.5 else 1)
f1['class'] = y
print("Accuracy:")
f1.loc[f1['pred']==f1['class']].shape[0] / f1.shape[0] * 100

Accuracy:


50.0

**Реализуйте метод градиентного спуска.** 

Обучите логистическую регрессию этим методом. Выберете и посчитайте метрику качества. Метрика должна быть одинакова для всех пунктов домашнего задания. Для упрощения сравнения выберете только одну метрику.

In [ ]:
EPOCHS = 1000
LEARNING_RATE = 0.01

costs = []
preds = []
params = W
for _ in range(EPOCHS):
    predictions = sigmoid(X, params)
    preds.append(predictions)

    cost = loss(predictions, y)
    costs.append(cost)
    
    params[0] -= LEARNING_RATE * np.sum(predictions - y) / len(predictions)
    params[1] -= LEARNING_RATE * np.sum((predictions - y) * X[:,0]) / len(predictions)
    params[2] -= LEARNING_RATE * np.sum((predictions - y) * X[:,1]) / len(predictions)
    params[3] -= LEARNING_RATE * np.sum((predictions - y) * X[:,2]) / len(predictions)
    params[4] -= LEARNING_RATE * np.sum((predictions - y) * X[:,3]) / len(predictions)

In [ ]:
params

array([ 0.57742293,  1.03730479,  0.83697158, -1.93135268, -0.0703256 ])

In [ ]:
result = sigmoid(X, params)


In [ ]:
res = pd.DataFrame()

In [ ]:
f = pd.DataFrame(result)
f['pred'] = f[0].apply(lambda x : 0 if x < 0.5 else 1)
f['class'] = y
print("Accuracy (Loss minimization):")
f.loc[f['pred']==f['class']].shape[0] / f.shape[0] * 100


Accuracy (Loss minimization):


93.0